version: "3.0"
services:
  api:
    build:
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./:/srv/www/:delegated
    tmpfs:
      - /run
      - /tmp
      - /var/run
    restart: always
  bot:
    build:
      dockerfile: Dockerfile
      args:
        - EXECUTABLE=run-bot.sh
    environment:
      - ML_API="http://api/predict"
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    volumes:
      - ./:/srv/www/:delegated
    tmpfs:
      - /run
      - /tmp
      - /var/run
    restart: always
