version: "3.0"
services:
  api:
    image: bootcamp:latest
    build:
      dockerfile: Dockerfile.api
    ports:
      - 8000:8000
    volumes:
      - ./:/srv/www/:delegated
    tmpfs:
      - /run
      - /tmp
      - /var/run
    restart: always
    command: ./bin/scripts/run-api.sh

  bot:
    image: bootcamp:latest
    environment:
      - ML_API="http://api/predict"
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    volumes:
      - ./:/srv/www/:delegated
    tmpfs:
      - /run
      - /tmp
      - /var/run
    restart: always
    command: ./bin/scripts/run-bot.sh
