# fly.toml file generated for velvet-wolves-art-expert-api on 2023-04-13T12:59:23+03:00

app = "velvet-wolves-art-expert-api"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "ams"
processes = []

[build]
dockerfile = "Dockerfile.api"

[metrics]
port = 8000
path = "/metrics"

[[services]]
  internal_port = 8000
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
